[package]
name = "desktop_streamer"
version = "0.1.0"
edition = "2024"

[dependencies]
webrtc = { version = "0.6", features = ["minimal"] }
futures = "0.1"
tokio = { version = "1.0", features = ["rt"] }
