[package]
name = "desktop_streamer"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
screenshots = "0.8.10"
tokio = { version = "1.45.1", features = ["full"] }
axum = "0.8.4"
axum-server = "0.7.2"
tokio-util = "0.7.15"
